name: luvpark_get
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.25.45+46
# ios version version: 2.1.1+2

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  qr_flutter:
    git:
      url: https://github.com/theyakka/qr.flutter.git
  mask_text_input_formatter: ^2.4.0
  intl: ^0.19.0
  flutter_multi_formatter: ^2.4.1
  shimmer: ^3.0.0 
  shared_preferences: ^2.0.15  
  pinput: ^4.0.0
  app_settings: ^5.0.0
  encrypt: ^5.0.0
  cryptography: ^2.5.0
  http: ^0.13.4
  url_launcher: ^6.1.11
  webview_flutter_wkwebview: ^3.2.3
  webview_flutter_android: ^3.4.3
  webview_flutter: ^4.0.7
  animate_do: ^3.0.2
  local_auth: ^2.1.6
  percent_indicator: ^4.2.3 
  external_app_launcher: ^3.1.0
  gallery_saver: ^2.3.2
  screenshot: ^2.1.0
  encrypted_shared_preferences: ^3.0.1
  location_geocoder: ^1.0.5
  geocoding: ^2.1.0
  google_maps_flutter: ^2.5.0
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.3.0
  share_plus: ^7.2.1
  permission_handler: ^11.0.0
  sqflite: ^2.3.0
  timezone: ^0.9.2 
  email_validator: ^2.1.17
  flutter_rating_bar: ^4.0.1 
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2  
  get: ^4.6.6
  flutter_dotenv: ^5.1.0 
  google_directions_api: ^0.9.1
  google_places_for_flutter: ^1.0.1
  google_maps_utils: ^2.0.0+1 
  upgrader: ^9.0.0
  awesome_notifications: ^0.9.2
  sliding_up_panel: ^2.0.0+1
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0  
  rive: ^0.13.2
  flutter_image_compress: ^2.3.0
  location: ^6.0.2
  geolocator: ^10.1.1
  google_fonts: ^4.0.4
  map_picker: ^0.0.3
  flutter_svg: ^1.1.5 
  speech_to_text: ^6.6.0 
  provider: ^6.1.2
  image_picker: ^1.0.8
  iconify_flutter: ^0.0.5
  lucide_icons: ^0.257.0
  text_to_speech: ^0.2.3
  tutorial_coach_mark: ^1.2.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/dashboard_icon/
    - assets/dashboard_icon/commercial/
    - assets/dashboard_icon/private/
    - assets/dashboard_icon/marker_panel/
    - assets/dashboard_icon/street/
    - assets/dashboard_icon/valet/
    - assets/area_details/
    - assets/drawer_icon/ 
    - assets/legend/ 
    - assets/custom_map_style/map_style.json
    - assets/map_filter/
    - assets/map_filter/active/
    - assets/map_filter/inactive/
    - assets/details_logo/
    - assets/details_logo/blue/
    - assets/details_logo/green/
    - assets/details_logo/orange/
    - assets/details_logo/violet/
